[package]
name = "balik-db"
version = "0.1.0"
edition = "2024"
description = "A toy DBMS — fishy but functional"

[[bin]]
name = "balik-cli"
path = "src/main.rs"

[dependencies]
bytesize = "2.4.0"
clap = { version = "4.6.0", features = ["derive"] }
clap-verbosity-flag = { version = "3.0.4", features = ["tracing"] }
fastrand = "2.4.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlparser = "0.62.0"
toml = "0.8"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"
